version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nordicos_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: nordicos_awards
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - nordicos_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nordicos_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/nordicos_awards?authSource=admin
      - DATABASE_NAME=nordicos_awards
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAX_FILE_SIZE=10485760
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,mp4,mov,avi,wmv
      - ADMIN_EMAIL=admin@nordicosawards.com
      - ADMIN_PASSWORD=admin123
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - nordicos_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nordicos_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nordicos_network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: nordicos_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    depends_on:
      - mongodb
    networks:
      - nordicos_network

volumes:
  mongodb_data:
  backend_uploads:

networks:
  nordicos_network:
    driver: bridge